# -*- coding: utf-8 -*-
"""Kubric prem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15UMKk9a4Gb0tqTXI7Difx5ZANv_xTA6i
"""

import requests
import pandas
import scipy
import numpy
import sys


TRAIN_DATA_URL = "https://storage.googleapis.com/kubric-hiring/linreg_train.csv"
TEST_DATA_URL = "https://storage.googleapis.com/kubric-hiring/linreg_test.csv"


def predict_price(area) -> float:
    """
    This method must accept as input an array `area` (represents a list of areas sizes in sq feet) and must return the respective predicted prices (price per sq foot) using the linear regression model that you build.

    You can run this program from the command line using `python3 regression.py`.
    """
    response = requests.get(TRAIN_DATA_URL)
    # YOUR IMPLEMENTATION HERE
    ...
    Sheet_train = pd.read_csv(TRAIN_DATA_URL, header = None)
    

    area_train_pd = Sheet_train.iloc[0]
    area_train_pd = area_train_pd.iloc[1:]

    price_train_pd = train.iloc[1]
    price_train_pd = price_train_pd.iloc[1:]

    #sheet_test = pd.read_csv("linreg_test.csv")

    #x_test = np.array(sheet_test['area'])
    #y_test = np.array(sheet_test['price'])

    #y_pred = model.predict(x_test.reshape(-1, 1))

    #rmse = numpy.sqrt(numpy.mean((y_pred - y_test) ** 2))

    #rmse

    X = numpy.array(area_train_pd).reshape((-1, 1))
    Y = numpy.array(price_train_pd)

    model = LinearRegression()
    model.fit(X, Y)

    Y_pred = model.predict(area.reshape((-1, 1)))

    
    return Y_pred


if __name__ == "__main__":
    # DO NOT CHANGE THE FOLLOWING CODE
    from data import validation_data
    areas = numpy.array(list(validation_data.keys()))
    prices = numpy.array(list(validation_data.values()))
    predicted_prices = predict_price(areas)
    rmse = numpy.sqrt(numpy.mean((predicted_prices - prices) ** 2))
    try:
        assert rmse < 170
    except AssertionError:
        print(f"Root mean squared error is too high - {rmse}. Expected it to be under 170")
        sys.exit(1)
    print(f"Success. RMSE = {rmse}")

